### ISSUE TITLE
Loading... and invalid date...

### ISSUE THREAD

**Issue by princemaxwell** [linuxtuxie/MMM-SunnyPortal#4]
Hey, i am using SunnyPortal and i want to use the module for smartmirror.
I have configured it completely, but i get errors.

First i get "Loading..." for a long time, then the graphs are there but empty. The daily, monthly, annual and total yield is showing 0 kwh.

`[2020-12-26 05:18:16.457] [ERROR]  CSV download failed: Error: connect ECONNRESET 171.25.178.37:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'connect',
  address: '171.25.178.37',
  port: 443
}
[2020-12-26 05:18:16.488] [ERROR]  Whoops! There was an uncaught exception...
[2020-12-26 05:18:16.499] [ERROR]  TypeError: Cannot read property 'split' of undefined
    at Function.<anonymous> (/home/pi/MagicMirror/modules/MMM-SunnyPortal/node_helper.js:283:38)
    at applyArgs (/home/pi/MagicMirror/modules/MMM-SunnyPortal/node_modules/flow/flow.js:9:15)
    at flowState (/home/pi/MagicMirror/modules/MMM-SunnyPortal/node_modules/flow/flow.js:39:6)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-SunnyPortal/node_helper.js:205:5)
    at self.callback (/home/pi/MagicMirror/modules/MMM-SunnyPortal/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (/home/pi/MagicMirror/modules/MMM-SunnyPortal/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
[2020-12-26 05:18:16.506] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-12-26 05:18:16.508] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2020-12-26 05:18:16.515] [ERROR]  Setting File Date failed: Error: connect ECONNRESET 171.25.178.37:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'connect',
  address: '171.25.178.37',
  port: 443
}
[2020-12-26 05:18:16.542] [ERROR]  Setting File Date failed: Error: socket hang up
    at connResetException (internal/errors.js:559:14)
    at TLSSocket.socketOnEnd (_http_client.js:436:23)
    at TLSSocket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  code: 'ECONNRESET'
}
[2020-12-26 05:18:16.574] [ERROR]  Setting File Date failed: Error: socket hang up
    at connResetException (internal/errors.js:559:14)
    at TLSSocket.socketOnEnd (_http_client.js:436:23)
    at TLSSocket.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  code: 'ECONNRESET'
}`

`[2020-12-26 05:17:52.228] [LOG]    Cookie Value: ASP.NET_SessionId=2rzwayqavbxcvbomc; BIGipServerPool_P_SunnyPortal=3104090304.20480.0000
[2020-12-26 05:17:52.233] [LOG]    Fetched VIEWSTATE value: lpqXi3JF...
[2020-12-26 05:17:52.236] [LOG]    Fetched VIEWSTATEGENERATOR value: 4E44AF44
[2020-12-26 05:17:52.289] [LOG]    Cookie Value: ASP.NET_SessionId=3xqvgd0g3vxydvxvcvvq; BIGipServerPool_P_SunnyPortal=3137644736.20480.0000
[2020-12-26 05:17:52.290] [LOG]    Fetched VIEWSTATE value: A5XPv7Hq...
[2020-12-26 05:17:52.291] [LOG]    Fetched VIEWSTATEGENERATOR value: 4E44AF44
[2020-12-26 05:17:52.327] [LOG]    Cookie Value: ASP.NET_SessionId=qnctrh11w4sfdsfsdfcnasl; BIGipServerPool_P_SunnyPortal=3154421952.20480.0000
[2020-12-26 05:17:52.328] [LOG]    Fetched VIEWSTATE value: S57Y8Kjw...
[2020-12-26 05:17:52.329] [LOG]    Fetched VIEWSTATEGENERATOR value: 4E44AF44
[2020-12-26 05:17:52.385] [LOG]    Cookie Value: ASP.NET_SessionId=dugsfdsdfsdfaso0uizaiwe; BIGipServerPool_P_SunnyPortal=3036981440.20480.0000
[2020-12-26 05:17:52.386] [LOG]    Fetched VIEWSTATE value: OXWiDiNz...
[2020-12-26 05:17:52.386] [LOG]    Fetched VIEWSTATEGENERATOR value: 4E44AF44
[2020-12-26 05:17:52.824] [INFO]   Calendar-Fetcher: Broadcasting 3 events.
[2020-12-26 05:17:53.503] [INFO]   Newsfeed-Fetcher: Broadcasting 100 items.
[2020-12-26 05:17:56.463] [INFO]   Calendar-Fetcher: Broadcasting 0 events.
[2020-12-26 05:17:56.497] [LOG]    SUCCESSFULLY LOGGED IN TO /FixedPages/Dashboard.aspx
[2020-12-26 05:17:56.546] [LOG]    SUCCESSFULLY LOGGED IN TO /FixedPages/Dashboard.aspx
[2020-12-26 05:17:56.572] [LOG]    SUCCESSFULLY LOGGED IN TO /FixedPages/Dashboard.aspx
[2020-12-26 05:17:56.591] [LOG]    SUCCESSFULLY LOGGED IN TO /FixedPages/Dashboard.aspx
[2020-12-26 05:17:58.793] [INFO]   Calendar-Fetcher: Broadcasting 10 events.
[2020-12-26 05:17:59.179] [LOG]    HTTP Result: 200
[2020-12-26 05:17:59.183] [LOG]    Fetched ctl00_HiddenPlantOID value: 11111111-2222-3333-4444-555555555555
[2020-12-26 05:17:59.246] [LOG]    HTTP Result: 200
[2020-12-26 05:17:59.252] [LOG]    Fetched ctl00_HiddenPlantOID value: 11111111-2222-3333-4444-555555555555
[2020-12-26 05:17:59.357] [LOG]    HTTP Result: 200
[2020-12-26 05:17:59.359] [LOG]    Fetched ctl00_HiddenPlantOID value: 11111111-2222-3333-4444-555555555555
[2020-12-26 05:17:59.360] [LOG]    Skip setting date because we are requesting power data from today
[2020-12-26 05:17:59.391] [LOG]    HTTP Result: 200
[2020-12-26 05:17:59.392] [LOG]    Fetched ctl00_HiddenPlantOID value: 11111111-2222-3333-4444-555555555555
[2020-12-26 05:18:16.436] [INFO]   Calendar-Fetcher: Broadcasting 10 events.
[2020-12-26 05:18:43.595] [INFO]   Calendar-Fetcher: Broadcasting 10 events.
[2020-12-26 05:18:44.132] [LOG]    HTTP Result: 200
[2020-12-26 05:18:44.137] [LOG]    Starting function processTotalData with data: 12:15 AM,12:30 AM,12:45 AM,1:00 AM,1:15 AM,1:30 AM,1:45 AM,2:00 AM,2:15 AM,2:30 AM,2:45 AM,3:00 AM,3:15 AM,3:30 AM,3:45 AM,4:00 AM,4:15 AM,4:30 AM,4:45 AM,5:00 AM,5:15 AM,5:30 AM,5:45 AM,6:00 AM,6:15 AM,6:30 AM,6:45 AM,7:00 AM,7:15 AM,7:30 AM,7:45 AM,8:00 AM,8:15 AM,8:30 AM,8:45 AM,9:00 AM,9:15 AM,9:30 AM,9:45 AM,10:00 AM,10:15 AM,10:30 AM,10:45 AM,11:00 AM,11:15 AM,11:30 AM,11:45 AM,12:00 PM,12:15 PM,12:30 PM,12:45 PM,1:00 PM,1:15 PM,1:30 PM,1:45 PM,2:00 PM,2:15 PM,2:30 PM,2:45 PM,3:00 PM,3:15 PM,3:30 PM,3:45 PM,4:00 PM,4:15 PM,4:30 PM,4:45 PM,5:00 PM,5:15 PM,5:30 PM,5:45 PM,6:00 PM,6:15 PM,6:30 PM,6:45 PM,7:00 PM,7:15 PM,7:30 PM,7:45 PM,8:00 PM,8:15 PM,8:30 PM,8:45 PM,9:00 PM,9:15 PM,9:30 PM,9:45 PM,10:00 PM,10:15 PM,10:30 PM,10:45 PM,11:00 PM,11:15 PM,11:30 PM,11:45 PM,12:00 AM,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
[2020-12-26 05:18:44.156] [LOG]    HTTP Result: 200
[2020-12-26 05:18:44.161] [LOG]    Starting function processYearData with data: Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),Sun Dec 01 2019 12:00:00 GMT+0100 (Mitteleuropäische Normalzeit),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
[2020-12-26 05:18:44.181] [LOG]    HTTP Result: 200
[2020-12-26 05:18:44.188] [LOG]    Starting function processMonthData with data: Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,Invalid Date,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
[2020-12-26 05:18:44.691] [INFO]   Calendar-Fetcher: Broadcasting 10 events.`

**Comment by linuxtuxie** [comment]
Hi  princemaxwell,

After a long search I figured out that the website is making use of a hidden parameter called 'ClientBrowserVersion' which changes at each session. I think they recently changed the behavior of this parameter, as we can see in the login page's source code, they have commented out the jquery entry $('#ClientBrowserVersion').val(navigator.appVersion);
and are now setting their own value in the input field instead of asking the value via the navigator.appVersion browser object

![image](https://user-images.githubusercontent.com/59981870/103483410-6dcf0500-4de7-11eb-98c9-1c6f5c9aa8b6.png)

I just released version 1.4.0 of the MMM-SunnyPortal code to support this new behavior.

Regards,
Linuxtuxie
